version: "3.9"

services:
  agent-orchestrator:
    build: 
      context: ./agent-orchestrator
      dockerfile: Dockerfile
    container_name: agent-orchestrator
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY:?OPENAI_API_KEY must be set before starting Docker Compose}
    env_file:
      - agent-orchestrator/.env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 2s
      retries: 6
    networks:
      - agent-network

  orchestrator-web:
    build:
      context: ./agent-orchestrator/web
    ports:
      - "4173:80"
    depends_on:
      agent-orchestrator:
        condition: service_healthy
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge

volumes:
  logs:
    driver: local
