app = "ultimate-agent-api"
primary_region = "ord"
[build]
  dockerfile = "Dockerfile"
[env]
  PORT = "3000"
[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
