name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  node-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install root tools if any
        run: |
          npm ci --ignore-scripts || true
      - name: Install + test API
        working-directory: agent-orchestrator
        run: |
          npm ci --ignore-scripts || true
          npm run -s lint || true
          npm test || true
      - name: Install + test Web
        working-directory: agent-orchestrator/web
        run: |
          npm ci --ignore-scripts || true
          npm run -s lint || true
          npm test || true

  docker-build:
    runs-on: ubuntu-latest
    needs: node-checks
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: agent-orchestrator
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/ultimate-agent-api:ci-${{ github.sha }}
      - name: Build Web image
        uses: docker/build-push-action@v6
        with:
          context: agent-orchestrator/web
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/ultimate-agent-web:ci-${{ github.sha }}
