name: deploy-fly
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} --app ultimate-agent-api
        working-directory: agent-orchestrator
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: flyctl deploy --remote-only
        working-directory: agent-orchestrator
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-web:
    needs: deploy-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: agent-orchestrator/web
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
