name: publish
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Derive tags
        id: meta
        run: |
          echo "api=ghcr.io/${{ github.repository_owner }}/ultimate-agent-api" >> $GITHUB_OUTPUT
          echo "web=ghcr.io/${{ github.repository_owner }}/ultimate-agent-web" >> $GITHUB_OUTPUT
      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: agent-orchestrator
          push: true
          tags: |
            ${{ steps.meta.outputs.api }}:latest
            ${{ steps.meta.outputs.api }}:${{ github.sha }}
      - name: Build and push Web
        uses: docker/build-push-action@v6
        with:
          context: agent-orchestrator/web
          push: true
          tags: |
            ${{ steps.meta.outputs.web }}:latest
            ${{ steps.meta.outputs.web }}:${{ github.sha }}
